### ISSUE TITLE
Fast ancestor access instead of recursive access to parent

### ISSUE THREAD

**Issue by silkentrance** [amerine/acts_as_tree#61]
Is it possible for you to implement something like https://github.com/xavier/acts-as-tree-with-dotted-ids in order to make access to the ancestor axis a single query instead of many recursive queries?

**Comment by felixbuenemann** [comment]
I think it it out of the scope for this gem.

There are already many gems that implement more efficient tree algorithms like:

* [awesome_nested_set](https://github.com/collectiveidea/awesome_nested_set): Nested Sets
* [ancestry](https://github.com/stefankroes/ancestry): Path based (similar to what you mention above)

Or more efficient implementations of the classical parent based model:

* [closure_tree](https://github.com/mceachen/closure_tree): Appears to make clever use of JOINs to improve performance
* [activerecord-hierarchical_query](https://github.com/take-five/activerecord-hierarchical_query): Using recursive SQL queries (not exactly a "tree" gem)

In contrast `acts_as_tree` has implemented most tree traversal in pure ruby, which makes the code very easy to read, but is far from the most efficient implementation, so I would recommend against using it for large/deeply nested trees.

Given that there are lots of good alternatives, I don't see the point in trying to change this gems tree model, which would cause a lot of work to enable smooth transitions for existing users and duplicate work from other gems.

**Comment by rainchen** [comment]
agree with @felixbuenemann, this `acts_as_tree` gem is a very classical parent/children hierarchy that just requiring one parent_id column.

I used `awesome_nested_set` and `ancestry` in different projects for different use cases, since each solution has its own benefit and limitation.

Actually I had this experience: At first using `acts_as_tree` as the default solution, but later the feature was updated to require to use a more efficient hierarchy pattern. I have to switch to another gem, do db migration, and changes all the outdated codes.

It's not so easy since each hierarchy pattern requires different db structure, it's not just a simple "change config" work for using a hierarchy pattern.

So in personally, I think it's interesting that there is a tree solution gem that can adapt all these kind of hierarchy solutions, allowed to use DSL code like this:

```
class Category < ActiveRecord::Base
  acts_as_tree hierarchy_pattern: :parent_id_pattern
  # acts_as_tree hierarchy_pattern: :materialised_path_pattern # works like ancestry or acts-as-tree-with-dotted-ids
  # acts_as_tree hierarchy_pattern: :nested_set_pattern
end
```
with this I can just adding new columns when changing hierarchy pattern but keeping the rest codes(works like `devise` gem when adding new modules)

**Comment by silkentrance** [comment]
@felixbuenemann thanks for the advise. I will have a look at the other gems. Closing.
